package com.delivery.wewok.utils

const val KEY_EXTRA_WOK = "KEY_EXTRA_WOK"
const val IID = "IID"
const val USERNAME = "USERNAME"
const val FIRST_NAME = "FIRST_NAME"
const val LAST_NAME = "LAST_NAME"
const val USER_EMAIL = "USER_EMAIL"
const val USER_NUM = "USER_NUM"
const val USER_ADR = "USER_ADR"
const val USER_VILLE = "USER_VILLE"
const val MODE_WOK = "MODE_WOK"
const val MODE_EMPORTER = "MODE_EMPORTER"
const val MODE_LIVRAISON = "MODE_LIVRAISON"
const val FRAIS_LIVRAISON = "FRAIS_LIVRAISON"
const val CODE_ZONE = "CODE_ZONE"
const val ZONE_CHECKED = "ZONE_CHECKED"
const val ORDER_ID = "ORDER_ID"
const val CONNECTED = "CONNECTED"
const val SAVED_ORDERS = "SAVED_ORDERS"
